# -*- coding: utf-8 -*-
"""email_sender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ONu4u8fmagsYIaeTo4a48SbX8_-_MF8v
"""

# 필요한 패키지를 불러옵니다.

import pandas as pd
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import smtplib
from email.header import Header 
from email.utils import formataddr

# SMTP 접속을 위한 서버 정보 및 계정을 설정합니다.

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_USER = 'xxx'
SMTP_PASSWORD = "xxx"

# 이메일 유효성 검사 함수

def is_valid(addr):
    import re
    if re.match('(^[a-zA-Z-0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)', addr):
        return True
    else:
        return False

# 이메일 보내는 함수

def send_mail(addr, subj_layout, cont_layout, attachment=None):
    if not is_valid(addr):
        print("Wrong email: " + addr)
        return
    
    # 텍스트 파일
    msg = MIMEMultipart("alternative")
    # 첨부파일이 있는 경우 mixed로 multipart 생성
    if attachment:
        msg = MIMEMultipart('mixed')
    msg["From"] = formataddr((str(Header('인공지능팩토리', 'utf-8')), SMTP_USER))
    msg["To"] = addr
    msg["Subject"] = subj_layout
    contents = cont_layout
    text = MIMEText(_text = contents, _charset = "utf-8")
    msg.attach(text)
    # 첨부파일이 있으면
    if attachment:
        from email.mime.base import MIMEBase
        from email import encoders
        file_data = MIMEBase("application", "octect-stream")
        file_data.set_payload(open(attachment, "rb").read())
        encoders.encode_base64(file_data)
        import os
        filename = os.path.basename(attachment)
        file_data.add_header("Content-Disposition", 'attachment', filename=('UTF-8', '', filename))
        msg.attach(file_data)
    
    # smtp로 접속할 서버 정보를 가진 클래스변수 생성
    smtp = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT)
    # 해당 서버로 로그인
    smtp.login(SMTP_USER, SMTP_PASSWORD)
    # 메일 발송
    smtp.sendmail(SMTP_USER, addr, msg.as_string())
    # 닫기
    smtp.close()

# 이메일 내용 작성 함수

def instant_email(email, user_name, file_name):
    subject = '[개별공지] ' + user_name + '님의 연차휴가 사용 촉진 안내'
    content = """안녕하세요. """+ user_name + """님, 김태영입니다.

항상 업무하시느라 고생이 많습니다. 바쁜 일정 속에서도 건강과 휴식을 꼭 챙기시기 바랍니다. 이와 관련하여 연차휴가 사용 촉진을 위한 안내 및 확인서를 받기 위해 공지 메일을 보내드립니다.

1. 첨부된 문서를 확인합니다.
2. 확인이 완료되면 서명란인 "(인)"에 서명을 합니다.
3. 본 메일 회신으로 파일을 첨부해주시면 자동으로 문서가 등록됩니다.
4. 회신으로 하지않고 새 메일로 주시면 정상적으로 제출이 되지 않습니다.

참고로 본 메일은 어시에 의해 자동생성된 메일입니다. 문제 발생 시 연락부탁드립니다.

김태영 드림
"""
    send_mail(email, subject, content, attachment = file_name)

if __name__ == "__main__":

    df = pd.read_csv('contents.csv', skipinitialspace=True, header=None)

    for email, user_name in zip(df[0], df[1]):
        
        file_name = email + '_' + user_name + '.pdf'
        instant_email(email, user_name, file_name)

        print(user_name + '('+ email + ')'+ '님께 이메일을 전송하였습니다.')

